---
- include_vars: "gpgkey_{{ ansible_distribution_release }}.yml"

- block:
  - name: Add an apt key by id from a keyserver
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: "{{ gpg_key }}"
      state: present
    environment:
      "{{ proxy_env }}"

  - name: Set repo
    template: src=deb_repo.j2 dest={{ r_repo_dest }} mode=644 owner=root group=root

  - name: Update the Ubunty Repo
    apt: update_cache=yes
#  when: ansible_distribution_release == 'xenial'
