---

- include: checkR.yml

- block:
  - include: configure_repo_deb.yml
    when: ansible_os_family == 'Debian'

  - include: configure.yml
  - include: install.yml
  - file: path="{{ RStat }}" state=touch
  when: not RFlag.stat.exists
