---
- name: Copy namenode service script
  template:
    src: service-namenode.j2
    dest: "{{ hadoop_services_dir }}/service-namenode.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"

- name: Start namenode service
  shell: "{{ hadoop_services_dir }}/service-namenode.sh"
  args:
    executable: /bin/bash

- name: Copy namenode Monit script
  template:
    src: service-namenode.j2
    dest: "{{ hadoop_services_dir }}/service-namenode.sh"
  when: setup_monit

- name: Copy namenode Monit service
  template:
    src: monit-namenode.j2
    dest: /etc/monit.d/service-namenode
  when: setup_monit

- name: Copy secondary namenode service script
  template:
    src: service-secondary-namenode.j2
    dest: "{{ hadoop_services_dir }}/service-secondary-namenode.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_seconday_namenode'] }}"

- name: Start secondary namenode service
  shell: "{{ hadoop_services_dir }}/service-secondary-namenode.sh"
  args:
    executable: /bin/bash
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_seconday_namenode'] }}"

- name: Copy secondary namenode Monit script
  template:
    src: service-secondary-namenode.j2
    dest: "{{ hadoop_services_dir }}/service-secondary-namenode.sh"
  when: setup_monit

- name: Copy secondary namenode Monit service
  template:
    src: monit-secondary-namenode.j2
    dest: /etc/monit.d/service-secondary-namenode
  when: setup_monit

- name: Copy datanode service
  template:
    src: service-datanode.j2
    dest: "{{ hadoop_services_dir }}/service-datanode.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_datanodes'] }}"

- name: Start datanode service
  shell: "{{ hadoop_services_dir }}/service-datanode.sh"
  args:
    executable: /bin/bash
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_datanodes'] }}"

- name: Copy datanode Monit script
  template:
    src: service-datanode.j2
    dest: "{{ hadoop_services_dir }}/service-datanode.sh"
  when: setup_monit

- name: Copy datanode Monit service
  template:
    src: monit-datanode.j2
    dest: /etc/monit.d/service-datanode
  when: setup_monit

- name: Copy resource manager service script
  template:
    src: service-resource-manager.j2
    dest: "{{ hadoop_services_dir }}/service-resource-manager.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"

- name: Start resource manager service
  shell: "{{ hadoop_services_dir }}/service-resource-manager.sh"
  args:
    executable: /bin/bash

- name: Copy resource manager Monit script
  template:
    src: service-resource-manager.j2
    dest: "{{ hadoop_services_dir }}/service-resource-manager.sh"
  when: setup_monit

- name: Copy resource manager  Monit service
  template:
    src: monit-resource-manager.j2
    dest: /etc/monit.d/service-resource-manager
  when: setup_monit

- name: Copy node manager service
  template:
    src: service-nodemanager.j2
    dest: "{{ hadoop_services_dir }}/service-nodemanager.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_datanodes'] }}"

- name: Start node manager service
  shell: "{{ hadoop_services_dir }}/service-nodemanager.sh"
  args:
    executable: /bin/bash
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_datanodes'] }}"

- name: Copy node manager Monit script
  template:
    src: service-nodemanager.j2
    dest: "{{ hadoop_services_dir }}/service-nodemanager.sh"
  when: setup_monit

- name: Copy node manager Monit service
  template:
    src: monit-nodemanager.j2
    dest: /etc/monit.d/service-nodemanager
  when: setup_monit

#- name: Start Proxy Serverr Service
#  shell: "{{ hadoop_services_dir }}/service-proxy-server.sh"
#  args:
#    executable: /bin/bash


- name: Copy Job History service
  template:
    src: service-mr-job-history.j2
    dest: "{{ hadoop_services_dir }}/service-mr-job-history.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"


- name: Start Job History service
  shell: "{{ hadoop_services_dir }}/service-mr-job-history.sh"
  args:
    executable: /bin/bash

- name: Copy Job History Monit script
  template:
    src: service-mr-job-history.j2
    dest: "{{ hadoop_services_dir }}/service-mr-job-history.sh"
  when: setup_monit

- name: Copy Job History Monit service
  template:
    src: monit-mr-job-history.j2
    dest: /etc/monit.d/service-mr-job-history
  when: setup_monit

- name: Copy service to start all Hadoop services
  template:
    src: service-all-hadoop.j2
    dest: "{{ hadoop_services_dir }}/service-all-hadoop.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_clients'] }}"
  when: num_nodes|int == 1

######################################################################################
