---
- name: Create /tmp HDFS directory
  shell: "source /etc/profile && {{ hadoop_dir }}/{{ hadoop_expended_version }}/bin/hadoop fs -mkdir -p /tmp/hadoop-yarn/staging"
  args:
     executable: /bin/bash

- name: Changing permission of /tmp HDFS directory
  shell: "source /etc/profile && {{ hadoop_dir }}/{{ hadoop_expended_version }}/bin/hadoop fs -chmod 0777 /tmp"
  args:
     executable: /bin/bash

- name: Changing permission of /tmp/hadoop-yarn HDFS directory
  shell: "source /etc/profile && {{ hadoop_dir }}/{{ hadoop_expended_version }}/bin/hadoop fs -chmod 0755 /tmp/hadoop-yarn"
  args:
     executable: /bin/bash

- name: Changing permission of /tmp/hadoop-yarn/staging HDFS directory
  shell: "source /etc/profile && {{ hadoop_dir }}/{{ hadoop_expended_version }}/bin/hadoop fs -chmod 0777 /tmp/hadoop-yarn/staging"
  args:
     executable: /bin/bash

- name: Get the mr-history root location
  shell: "echo {{ maperd_dir }} | cut -d '/' -f2"
  args:
     executable: /bin/bash
  register: base_dir

- name: Changing permission of mr-history root HDFS directory
  shell: "source /etc/profile && {{ hadoop_dir }}/{{ hadoop_expended_version }}/bin/hadoop fs -chmod -R 0775 /{{ base_dir.stdout }}"
  args:
     executable: /bin/bash

- name: Changing permission of mr-history temporary HDFS directory
  shell: "source /etc/profile && {{ hadoop_dir }}/{{ hadoop_expended_version }}/bin/hadoop fs -chmod 0777 {{ maperd_dir }}/tmp"
  args:
     executable: /bin/bash
