---
- name: Copy Spark Master service script
  template:
    src: service-spark-master.j2
    dest: "{{ spark_services_dir }}/service-spark-master.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"

- name: Start Spark Master service
  shell: "{{ spark_services_dir }}/service-spark-master.sh"
  args:
    executable: /bin/bash

- name: Copy Spark Master Monit script
  template:
    src: service-spark-master.j2
    dest: "{{ spark_services_dir }}/service-spark-master.sh"
  when: setup_monit

- name: Copy Spark Master Monit service
  template:
    src: monit-spark-master.j2
    dest: /etc/monit.d/service-spark-master
  when: setup_monit

- name: Copy Spark History Server service script
  template:
    src: service-spark-history-server.j2
    dest: "{{ spark_services_dir }}/service-spark-history-server.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"

- name: Start Spark History Server service
  shell: "{{ spark_services_dir }}/service-spark-history-server.sh"
  args:
    executable: /bin/bash

- name: Copy Spark History Server Monit script
  template:
    src: service-spark-history-server.j2
    dest: "{{ spark_services_dir }}/service-spark-history.sh"
  when: setup_monit

- name: Copy Spark History Server Monit service
  template:
    src: monit-spark-history.j2
    dest: /etc/monit.d/service-spark-history
  when: setup_monit

- name: Copy Spark Slave service script
  template:
    src: service-spark-slave.j2
    dest: "{{ spark_services_dir }}/service-spark-slave.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['spark_slaves'] }}"

- name: Start Spark Slaves service
  shell: "{{ spark_services_dir }}/service-spark-slave.sh"
  args:
    executable: /bin/bash
  delegate_to: "{{ item }}"
  with_items: "{{ groups['spark_slaves'] }}"

- name: Copy Spark slave Monit script
  template:
    src: service-spark-slave.j2
    dest: "{{ spark_services_dir }}/service-spark-slave.sh"
  when: setup_monit

- name: Copy Spark slave Monit service
  template:
    src: monit-spark-slave.j2
    dest: /etc/monit.d/service-spark-slave
  when: setup_monit

- name: Copy service to start all Spark services
  template:
    src: service-all-spark.j2
    dest: "{{ spark_services_dir }}/service-all-spark.sh"
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_clients'] }}"
  when: num_nodes|int == 1
