---
- include: user.yml
- include: hdfs.yml
  become: true
  become_user: "{{ hadoop_user }}"

- name: Kill all previous hadoop services if any
  shell: "sudo /bin/sh {{ hadoop_dir }}/services/service-hadoop.sh"
  ignore_errors: yes
