---
- name: Create Download location
  file:
    path: "{{ package_download_dir }}"
    state: directory
    mode: 0755

- include: git.yml


- block:
  - include: python2_6_6.yml
  - include: pip.yml
  when: not setup_anaconda

- include: anaconda.yml
  when: setup_anaconda
