---
- name: Gathering Facts
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo


- name: Setup Hadoop prerequesite
  hosts: hadoop_namenode
  become: yes
  become_method: sudo
  roles:
  - startHadoopService
