---
# Install Pip packages
#
#

- name: Copy requirements.txt to remote machine
  copy:
    src: requirements.txt
    dest: "{{ python_pkgs_download_dir }}/requirements.txt"


- name: Installing pbr and traceback2 package
  shell: "source /etc/profile && pip install {{ item.name }}=={{ item.version }}"
  args:
    executable: /bin/bash
  with_items:
    - { name: 'pbr', version: '1.10.0' }
    - { name: 'linecache2', version: '1.0.0' }
    - { name: 'traceback2', version: '1.3.0' }
    - { name: 'six', version: '1.10.0' }
    - { name: 'argparse', version: '1.4.0' }

- name: Installing PIP packages
  shell: "source /etc/profile && pip install -r {{ python_pkgs_download_dir }}/requirements.txt"
  args:
    executable: /bin/bash

- name: Execute ldconfig
  shell: ldconfig
