---
- name: Set Google Chrome Repo
  template: src=Debian_chrome_repo.j2 dest={{ Debian_chrome_repo_dest }} mode=644 owner=root group=root

- name: Add Google Chrome key by URL from a keyserver
  apt_key:
    url: "{{ chrome_key_url }}"
    state: present
    validate_certs: no

- name: Update apt cache
  apt: update_cache=yes

- name: Install Google Chrome
  package: name={{ item }} state=latest
  with_items:
    - google-chrome-stable
