---

- name: Check if JDK module executed
  stat: path={{ jdkstat }}
  register: jdkstatflag

- block:
  - name: Install Java kit
    include: java.yml
    when: setup_java
  - file: path={{ jdkstat }} state=touch
  when: not jdkstatflag.stat.exists and setup_java
