---
- name: Remove git if present
  file: path={{ git_install_path }}s state=absent

- name: Create Git Dir
  file: path={{ git_install_path }}s state=directory

- name: Extract Git
  shell: "tar -zxvf {{ git_local_path }} -C {{ git_install_path }}"

- name: Compile Git
  shell: cd {{ git_install_path }}/git-{{ git_version }} ; make prefix={{ git_install_path }} all

- name: Make Git binary
  shell: cd {{ git_install_path }}/git-{{ git_version }} ; make prefix={{ git_install_path }} install

- name: Cleanup post git build
  file: path={{ git_install_path }}/git-{{ git_version }} state=absent

- name: Set GIT_HOME
  template: src=git_path.j2 dest={{ git_profile_path }} mode=0755
