---
- name: Uninstall git if present
  package: name=git state=absent

- name: Create Git Dir
  file: path={{ git_install_path }}/bin state=directory

- name: Extract Git
  unarchive: src={{ git_local_path }} dest={{ git_install_path }} remote_src=yes

- name: Compile Git for CentOS 7
  shell: cd {{ git_install_path }}/git-2.0.4 ; ./configure  all

- name: Make Git binary
  shell: cd {{ git_install_path }}/git-2.0.4 ; make all

- name: Copy the git to GIT_HOME bin
  copy: remote_src=True src={{ git_install_path }}/git-2.0.4/git dest={{ git_install_path }}/bin mode=0755

- name: Cleanup post git build
  file: path={{ git_install_path }}/git-2.0.4 state=absent

- name: Set GIT_HOME
  template: src=git_path.j2 dest={{ git_profile_path }} mode=0755
