---
- name: Remove git if present
  file: path={{ git_install_path }} state=absent

- name: Create Git Dir
  file: path={{ git_install_path }} state=directory

- name: Extract Git
  unarchive: src={{ git_local_path }} dest={{ git_install_path }} mode=0755 remote_src=yes

- name: Compile Git
  shell: cd {{ git_install_path }}/git-{{ git_version }} ; make prefix={{ git_install_path }} all

- name: Make Git binary
  shell: cd {{ git_install_path }}/git-{{ git_version }} ; make prefix={{ git_install_path }} install

- name: Cleanup post git build
  file: path={{ git_install_path }}/git-{{ git_version }} state=absent

- name: Set GIT_HOME
  template: src=git_path.j2 dest={{ git_profile_path }} mode=0755
