---

- name: Check if Git module executed
  stat: path={{ gitstat }}
  register: gitstatflag

- block:
  - name: Install Git
    include: git.yml

  - file: path={{ gitstat }} state=touch
  when: not gitstatflag.stat.exists
